name: workflow trigger

on:
  push:
    branches:
      - "main"

jobs: 
  my-workflow-job:
    name: workflow
    runs-on: ubuntu-latest

    steps:
      - name : checkout code 
        run: actions/checkout@v4
        

      - name: setup docker build
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build the docker 
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: Yousef-Zeer/java-app:$GITHUB_REF


